SLACK_TOKEN: ENC[AES256_GCM,data:PFWOF5HMTJzFcHn/kPK5j8Us0zoSpvK6yQT3Wz5i1a8K/QWSoX3GJu8spoxf9o4B94RJZBN+/7cZ,iv:s3BJZmlP96dviWP1wCv3fC0QL7liDzdJUSb2OakxY18=,tag:L/h9OYSs92w5pDp6cS9tUg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:937168356724:key/a98e89a6-7d5d-4929-9e5a-b9412f220ac3
          created_at: "2022-12-30T17:13:10Z"
          enc: AQICAHi1l7NWvJ+Px5ohWqCgtxR8PhKV7F+BQtqo4/3aMN2K6gFDo7MTmQbv3QySv25LyKDmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM8gag/ESNotWQhO/DAgEQgDttE/aKWhSibckm6wv5b7ecQNKbuoK7IVn0Iw55PQBDi3OCb1Ek+E2nEWUB1li2NwBDw0tXzsU1hc7pag==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-30T17:13:10Z"
    mac: ENC[AES256_GCM,data:wIroe3mk8HZVZml4MS1DZzL/lKTFUK7JuXuR4rRGvrAfGTNqDeE+XO7SWIC3pD5ikd/21vXoU01lKgjcsAVujt1+0aEVxrM3jlTLZV+03+yh9aEHgJzcCTHZrGGm3OKplxyi1qfv5W4Mmx8C+M20O7onCXynZ8TYFHeDSwai8hM=,iv:UWKnHPWhnSvlLC9WhQHoWScC8zI3395wuk8DBqJztyM=,tag:zmNzUcT5GmaoFOLGqzrGGA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
